experiment_name: Part1_Exp1_1_GCN60
seed: 42
device: cuda

dataset_params:
  path: Data
  train_split: Train
  test_split: Test
  beat_size_before: 100
  beat_size_after: 180
  graph_constructor: vg
  feature_set: raw
  undersampling_ratio: 0.1
  undersampling_method: stride
  undersample_test: true
  paradigm: inter
  val_from_train_ratio: 0.2
  preprocess_workers: 0

training:
  batch_size: 32
  learning_rate: 0.001
  epochs: 150

model_params:
  model_name: gcn60
  in_channels: 1
  num_classes: 3
  readout: mean