experiment_name: "Part2_exp_GINESeq2Seq"
seed: 42
device: cuda

dataset_params:
  path: Data
  train_split: Train
  test_split: Test
  beat_size_before: 120
  beat_size_after: 120
  graph_constructor: vg
  feature_set: rr
  edge_features: [delta_t, slope, length]
  k_limit: 30
  preprocess_workers: 0
  undersampling_ratio: 0.1
  undersampling_method: stride
  undersample_test: true
  val_from_train_ratio: 0.2
  paradigm: inter

data_loader_params:
  sequence_length: 10

model_params:
  model_name: "GINESeq2Seq"
  model_type: "seq2seq_gnn"

  gine_config:
    in_channels: 5       # Ajuste conforme features de nó usadas
    edge_dim: 3          # Ajuste conforme edge features usadas
    hidden_channels: 128
    num_layers: 5
    readout: "mean"

  encoder:
    hidden_size: 128
    num_layers: 1

  decoder:
    hidden_size: 128
    num_layers: 1
    teacher_forcing: true

  classifier:
    num_classes: 3

training:
  batch_size: 8
  learning_rate: 1.0e-4
  weight_decay: 0.01
  warmup_ratio: 0.1
  grad_clip_max_norm: 1.0
  epochs: 150
  class_weights_mode: effective
  class_weights_beta: 0.9999
